application:
  subdomain: logbull
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://logbull:4005/
services:
  logbull:
    # upstream: docker.io/logbull/logbull:v0.28.1
    image: registry.lazycat.cloud/czyt/logbull/logbull:5db06248c3c7b81c
    binds:
      - /lzcapp/var/data:/logbull-data
