application:
  subdomain: logbull
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://logbull:4005/

services:
  logbull:
    # upstream: docker.io/logbull/logbull:v0.6.2
    image: registry.lazycat.cloud/czyt/logbull/logbull:76fdab7f67ec74e7
    binds:
      - /lzcapp/var/data:/logbull-data
