name: Log Bull
package: community.lazycat.app.logbull
version: 0.6.2
min_os_version: 1.3.8
description: 简单的日志收集和查看系统
homepage: https://github.com/logbull/logbull
author: logbull
application:
  subdomain: logbull
  background_task: true
  public_path:
    - /

  upstreams:
    - location: /
      backend: http://logbull:4005/

services:
  logbull:
    container_name: logbull
    #  logbull/logbull:v0.6.2
    image: registry.lazycat.cloud/czyt/logbull/logbull:76fdab7f67ec74e7
    binds:
      - /lzcapp/var/data:/logbull-data

locales:
  zh:
    name: "Log Bull"
    description: "简单的日志收集和查看系统"
  zh_CN:
    name: "Log Bull"
    description: "简单的日志收集和查看系统"
  en:
    name: "Log Bull"
    description: "simple log collection and view system"
